# Generated by Django 3.1.4 on 2020-12-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201216_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='cover_img',
        ),
    ]
